# Generated by Django 5.1 on 2026-04-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_items_order_payment_info_delete_orderitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order_summary',
        ),
    ]
